### ISSUE TITLE
Is there a license for this repository?

### ISSUE THREAD

**Issue by kiddfc** [DiamondLightSource/PuckBarcodeReader#88]
Hi everyone,
I am working on a data matrix detection function. At this point it's for some research purposes, but it might end up in a commercial product.
I want to adapt some of the ideas you have in this repository to my code. Is there a license for the use of the code?
Thanks,

**Comment by UrszulaNeuman** [comment]
Hi,
license file added to the repo. 
Cheers,
Urszula
